services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-erplay}
      MYSQL_USER: ${MYSQL_USER:-erplay}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-erplay}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD:-rootpass}"]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8080}
      PUBLIC_API_BASE_URL: ${PUBLIC_API_BASE_URL:-http://localhost:3000}
      APP_URL: ${APP_URL:-http://localhost:3000}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER:-erplay}
      DB_PASSWORD: ${MYSQL_PASSWORD:-erplay}
      DB_NAME: ${MYSQL_DATABASE:-erplay}
      JWT_SECRET: 9f4a1e7c2d5b8f0134c6e2a8b7d8f0a1c3e5b6d7a8c9e0f1b2c3d4e5f6a7b82
      JWT_REFRESH_SECRET: 3b1f2c4d5e6a7b8c9d0e1f223b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1z
      JWT_RESET_SECRET: 3b1f2c4d5e6a7bbh9d0e1f223b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f3dza
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_USER: erplay.contact@gmail.com
      SMTP_PASS: tygv synh whha lcnf
      RUN_DB_SEED: ${RUN_DB_SEED:-false}   # ðŸ‘ˆ por defecto NO hace seed
    ports:
      - "3000:3000"
    volumes:
      - back_uploads:/app/uploads


  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
    depends_on:
      back:
        condition: service_started
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production

volumes:
  db_data:
  back_uploads:
